from datetime import datetime


class Position:
    """
    The trade information with price and amount etc.

    :member
        price: The trading price in quote currency.
        amount: The trading volume in base currency.
        trade_id: The unique trade id of this trade.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        direction: The direction of the taker trade: 'buy' or 'sell'.
    """

    def __init__(self):
        self.volume = 0.0
        self.timestamp = 0

    @staticmethod
    def json_parse(json_data):
        position = Position()
        position.volume = json_data.get_float("volume")
        position.timestamp = json_data.get_int("ts")
        return position

    def print_object(self, format_data=""):
        from huobi.base.printobject import PrintBasic
        t2 = self.timestamp / 1000
        date_time = datetime.fromtimestamp(t2).strftime("%Y-%m-%d, %H:%M:%S")
        PrintBasic.print_basic(self.volume, format_data + "Position")
        PrintBasic.print_basic(date_time, format_data + "Trade Time")
