from datetime import datetime

class Ttmu:
    """
    The trade information with price and amount etc.

    :member
        price: The trading price in quote currency.
        amount: The trading volume in base currency.
        trade_id: The unique trade id of this trade.
        timestamp: The UNIX formatted timestamp generated by server in UTC.
        direction: The direction of the taker trade: 'buy' or 'sell'.
    """

    def __init__(self):
        self.buy_ratio = 0.0
        self.sell_ratio = 0.0
        self.timestamp = 0

    @staticmethod
    def json_parse(json_data):
        ttmu = Ttmu()
        ttmu.buy_ratio = json_data.get_float("buy_ratio")
        ttmu.sell_ratio = json_data.get_float("sell_ratio")
        ttmu.timestamp = json_data.get_int("ts")
        return ttmu

    def print_object(self, format_data=""):
        from huobi.base.printobject import PrintBasic
        t2 = self.timestamp / 1000
        date_time = datetime.fromtimestamp(t2).strftime("%Y-%m-%d, %H:%M:%S")
        PrintBasic.print_basic(self.buy_ratio, format_data + "buy_ratio")
        PrintBasic.print_basic(self.sell_ratio, format_data + "sell_ratio")
        PrintBasic.print_basic(date_time, format_data + "Trade Time")
